// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUsQ6DunUZ_qBZ_1kICiMiopy99Di4CKo',
    appId: '1:859334905645:web:4f10a05b82f3f5ea354da4',
    messagingSenderId: '859334905645',
    projectId: 'animu-7037a',
    authDomain: 'animu-7037a.firebaseapp.com',
    storageBucket: 'animu-7037a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_AM-XDSPPABCVnaD-lL7s6aFt6DK4pbE',
    appId: '1:859334905645:android:1978e829c0cb7f9a354da4',
    messagingSenderId: '859334905645',
    projectId: 'animu-7037a',
    storageBucket: 'animu-7037a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRxtunqhdfn_3mxl1eQGpwHE4IIkpDuVg',
    appId: '1:859334905645:ios:265ff1858b26ec9d354da4',
    messagingSenderId: '859334905645',
    projectId: 'animu-7037a',
    storageBucket: 'animu-7037a.firebasestorage.app',
    iosBundleId: 'com.animu.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRxtunqhdfn_3mxl1eQGpwHE4IIkpDuVg',
    appId: '1:859334905645:ios:832166ad401ae229354da4',
    messagingSenderId: '859334905645',
    projectId: 'animu-7037a',
    storageBucket: 'animu-7037a.firebasestorage.app',
    iosBundleId: 'com.example.aninmeLibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUsQ6DunUZ_qBZ_1kICiMiopy99Di4CKo',
    appId: '1:859334905645:web:de9b4b6eb466fdb1354da4',
    messagingSenderId: '859334905645',
    projectId: 'animu-7037a',
    authDomain: 'animu-7037a.firebaseapp.com',
    storageBucket: 'animu-7037a.firebasestorage.app',
  );

}